name: Daily Vocabulary

on:
  schedule:
  # Runs every day at 11:09 AM IST
  # 11:09 AM IST = 05:39 AM UTC
  - cron: "39 5 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-vocabulary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --locked

      - name: Run Vocab with Mama
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: uv run python app/main.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/

          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "chore: update daily vocabulary"
            git push
          fi